name: StairBuilder
main: com.eatsleepcode.stairbuilder.StairBuilder
version: 2025.02.01.22
api: [1.0.11]
author: eat-sleep-code
description: Build a lighted staircase descending to the specified depth coordinate.
commands:
  stairs:
    description: Build a lighted staircase descending to the specified depth coordinate.
    usage: /stairs <depth>
    permission: stairs.create
